---
book_repo: cloudfoundry/docs-book-cloudfoundry

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.cloudfoundry.org

sections:
- repository:
    name: cloudfoundry/docs-buildpacks
    ref: master
  directory: buildpacks
  subnav_template: cf-subnav.erb
  dependent_sections:
  - repository:
      name: cloudfoundry-samples/pong_matcher_grails
    no_docs: true
  - repository:
      name: cloudfoundry-samples/pong_matcher_groovy
    no_docs: true
  - repository:
      name: cloudfoundry-samples/pong_matcher_spring
    no_docs: true
  - repository:
      name: cloudfoundry-samples/pong_matcher_ruby
    no_docs: true
- repository:
    name: cloudfoundry/docs-bbr
    ref: master
  directory: bbr
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-cf-admin
    ref: master
  directory: adminguide
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-cf-cli
    ref: master
  directory: cf-cli
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-cloudfoundry-concepts
    ref: master
  directory: concepts
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-credhub
    ref: master
  directory: credhub
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-deploying-cf
    ref: master
  directory: deploying
  subnav_template: cf-subnav.erb
  dependent_sections:
  - repository:
      name: cloudfoundry/cf-release
    no_docs: true
- repository:
    name: cloudfoundry/docs-dev-guide
    ref: master
  directory: devguide
  subnav_template: cf-subnav.erb
  dependent_sections:
  - repository:
      name: cloudfoundry-samples/pong_matcher_spring
    no_docs: true
- repository:
    name: cloudfoundry/docs-loggregator
    ref: master
  directory: loggregator
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-running-cf
    ref: master
  directory: running
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-services
    ref: master
  directory: services
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-uaa
    ref: master
  directory: uaa
  subnav_template: cf-subnav.erb
